### ISSUE TITLE
stripTruthStackFrames for ComparisonFailure, too

### ISSUE THREAD

**Issue by cpovirk** [google/truth#276]
To cut out this kind of thing:

    at com.google.common.truth.Platform.comparisonFailure(Platform.java:126)
    at com.google.common.truth.Truth$1.failComparing(Truth.java:72)
    at com.google.common.truth.ThrowableSubject$1.failComparing(ThrowableSubject.java:85)
    at com.google.common.truth.ThrowableSubject$2.failComparing(ThrowableSubject.java:116)
    at com.google.common.truth.StringSubject.isEqualTo(StringSubject.java:70)
    at com.google.common.truth.ThrowableSubject.hasMessage(ThrowableSubject.java:43)

**Comment by dimo414** [comment]
I think this is fixed as of e319cf489e, though I haven't explicitly tested it.

**Comment by dimo414** [comment]
Verified, traces are now stripped on assertions that rely on both `fail()` and `failComparing()`.
