### ISSUE TITLE
Truth seems to import JUnit 4, even on JUnit 5

### ISSUE THREAD

**Issue by jbduncan** [google/truth#333]
It occurs to me that the `core/` subproject's pom.xml imports JUnit 4 as a non-test dependency. I think this is fine for projects that use JUnit 4 and Truth together for testing, but I'm a little concerned that for projects using JUnit 5 it will cause JUnit 4 to be unnecessarily downloaded and depended upon.

Are there any plans to move any parts of Truth which depend on JUnit 4 APIs into their own extensions?

**Comment by cpovirk** [comment]
Unfortunately, the parts of Truth that depend on JUnit 4 are basically all "all of them," since [we throw `ComparisonFailure`](https://github.com/google/truth/blob/794c31a2bc39670c7ab6bc2b884849442f5c0ee3/core/src/main/java/com/google/common/truth/Truth.java#L88).

There are at least a couple approaches we could take here:

- Throw `ComparisonFailure` conditionally only if it's available at runtime.
- Adopt the [opentest4j](https://github.com/ota4j-team/opentest4j) types once they're finalized.

Overall, I'm not too concerned about a dependency on JUnit 4 in Truth, since it's a test framework. But if it's causing people trouble, we should reconsider.

**Comment by dimo414** [comment]
Throwing `ComparisonFailure` only if it's already on the classpath would be a silent regression for users not using JUnit4, so (as you say, assuming it's not causing real trouble) I think waiting for opentest4j makes the most sense.

**Comment by kashike** [comment]
opentest4j 1.0.0 was [released on September 10th](https://github.com/ota4j-team/opentest4j/releases/tag/r1.0.0).

**Comment by cpovirk** [comment]
Cool, thanks.

**Comment by Androbin** [comment]
Since #40 is merged, we can close this now.

**Comment by jbduncan** [comment]
@Androbin Sorry, I'm unclear on how #40 is related to this issue. Would you kindly clarify things for me?

**Comment by Androbin** [comment]
Oops, I meant https://github.com/square/misk/pull/40

**Comment by cpovirk** [comment]
Oh, thanks for the link:

> Until this is resolved, we should be careful to use the `@org.junit.jupiter.api.Test` annotation and not `@org.junit.Test` by mistake.

That's a good downside for us to keep in mind. Inside Google, I think we're pretty much resigned to having JUnit 4 on our classpath, and people haven't started using JUnit 5 much. But externally, things are different.

This is still something we could consider doing someday. It's just not at the top of the list currently.

**Comment by Androbin** [comment]
Isn't there a way to search & replace "en masse" across the codebase?
Or is this simply not feasible?

**Comment by cpovirk** [comment]
We can do search and replace. My fears are:

- Some people will be catching particular exception types, and their code will break. They ideally wouldn't be doing that, but we still have to clean them up inside Google, and others will have to fix it outside Google :\ Of course, the sooner we make the change, the better, so that the fallout is smaller.

- We'd need to get the opentest4j exceptions working under GWT and Android -- which is _probably_ straightforward but sometimes turns out not to be.

- The opentest4j annotations still look possibly not officially finalized -- or maybe the docs just haven't been updated yet, since they're used in JUnit 5?

None of these are necessarily huge problems; there just didn't seem to be a big upside to eliminating the JUnit 4 dependency. The release of JUnit 5 may change that, and it calls attention to a larger problem with multiple `@Test` annotations.

**Comment by cpovirk** [comment]
Oh, and we should also check whether IDEs have begun supporting the opentest4j `AssertionFailedError`. I gather that they probably have, but I'd want to be sure. (e.g., I found [this comment suggesting that IntelliJ has problems](https://github.com/joel-costigliola/assertj-core/issues/1072#issuecomment-331724910), but it seems hard to believe. I'd still want to verify.)

**Comment by childnode** [comment]
@Androbin 
> Isn't there a way to search & replace "en masse" across the codebase?
> Or is this simply not feasible?

just have a look what the gradle guys do with their codebase: https://github.com/gradle/gradle/pull/4116 << tl;dr: auto converting and running junit 4 tests with junit 5 platform both vintage and converted https://github.com/gradle/gradle/pull/4116/files#diff-a5945fda2451f7bab0e91c578e8e7f2eR49 ff

**Comment by cpovirk** [comment]
We should at least consider migrating to the new extensions before 1.0. My guess is that we'll ultimately not consider this to be a true 1.0 blocker, but I'll mark it for consideration.

**Comment by cpovirk** [comment]
This might include eliminating `TruthJUnit` in favor of something on `Truth` itself.

Alternatively, it might include concluding that `TruthJUnit` is a weird name for a class that contains `assume` -- and then doing something about that.

**Comment by cpovirk** [comment]
Another thing that `opentest4j` offers is `MultipleFailuresError`, which would be nice for `Expect`.

**Comment by ptahchiev** [comment]
This issue is blocking me to migrate to JUnit5 :( I use google-compile testing framework which brings truth as transitive dependency and you guys have hard-coded junit4 classes in there (`JUnitComparisonFailure`)

**Comment by cpovirk** [comment]
My current thinking is that we won't fix this for 1.0 (which we're going to try to make our final release with breaking changes) because we can still theoretically fix it afterward by:
- changing our calls to `FailureStrategy.fail` to pass an `AssertionFailedError` (a subtype of `AssertionError`)
- making JUnit 4 an `optional` dependency that users can add if they want to use `TruthJUnit`
I still hope to have a look at all that someday, but it's not imminent.

**Comment by cpovirk** [comment]
Oh, and I meant to add that, as part of opentest4j support, we'd also want to look for the opentest4j `IncompleteExecutionException` (and subtypes) [in `Expect`](https://github.com/google/truth/blob/e7deeea19d632af076fb7895b2f4117d01706d89/core/src/main/java/com/google/common/truth/Expect.java#L193).

**Comment by jbduncan** [comment]
Sounds good to me @cpovirk! 👍

**Comment by ptahchiev** [comment]
Any updates on this? I'd really like to see you guys support JUnit5 so we can move the google-compile-testing to JUnit5 too.

**Comment by stolsvik** [comment]
We use truth in some of our projects along with JUnit 5 (Jupiter), and due to this hard JUnit 4 dep we get an annoying "no [junit 4] tests found" message, in red (IntelliJ!), over 4 lines for each test run we do. It is a broken window, thorn in my side that really is putting me off this combo.

Why can't you instead throw AssertionError with a message or somesuch if JUnit 4 is not on the classpath?

**Comment by cpovirk** [comment]
Thanks. It's helpful to hear of a concrete problem this is causing -- but of course it's sad to hear that such a problem exists :(

Since your goal isn't to gain features from the new opentest4j types but rather just to _work_ without JUnit 4 on the classpath, I suspect that we can hack something up. I will try to give it a shot in the next week or so, though no 100% guarantee on that.

(I wonder if IntelliJ could also be changed to avoid issuing this error. If you've done any digging into their forums or issue tracker, I'd be happy to follow along with anything you've found. But I certainly don't want to pressure you to spend more time on this than you have already.)

**Comment by cpovirk** [comment]
@stolsvik, please try [version 1.1.1](https://github.com/google/truth/releases/tag/release_1_1_1) and let me know if that resolves the problem you are encountering.

**Comment by tbroyer** [comment]
Fwiw, I use with success:
```kotlin
    testImplementation("com.google.truth:truth:1.1") {
        // See https://github.com/google/truth/issues/333
        exclude(group = "junit", module = "junit")
    }
    testRuntimeOnly("junit:junit:4.13") {
        // See https://github.com/google/truth/issues/333
        because("Truth needs it")
    }
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.0")
```
https://github.com/tbroyer/gradle-nullaway-plugin/blob/b87e1f5f0a782944717a4bd1f594fd8566f4ff5c/build.gradle.kts#L61-L70

My tests are in Kotlin and not Java, but IntelliJ IDEA (2020.3.1) doesn't complain.
I'm also using `TruthJUnit.assume()` with no problem as JUnit 4 types are not exposed in the API (if Truth were built with Gradle, it'd be a perfect case for `implementation` vs `api`, where Gradle would generate a `<scope>runtime</scope>` in the published POM).

As an exercise, I tried upgrading to Truth 1.1.1 and removing the `testRuntimeOnly("junit:junit:4.13")`, after commenting out all my usages of `TruthJUnit` but that fails right from the `Truth` clinit:
```
java.lang.NoClassDefFoundError: org/junit/ComparisonFailure
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.google.common.truth.StandardSubjectBuilder.forCustomFailureStrategy(StandardSubjectBuilder.java:55)
	at com.google.common.truth.Truth.<clinit>(Truth.java:85)
	at net.ltgt.gradle.nullaway.AbstractPluginIntegrationTest.compilation succeeds(AbstractPluginIntegrationTest.kt:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[…]
Caused by: java.lang.ClassNotFoundException: org.junit.ComparisonFailure
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 111 more
```

**Comment by cpovirk** [comment]
Thanks, that is odd. The only mention of `org.junit.ComparisonFailure` in that release should be here:
https://github.com/google/truth/blob/release_1_1_1/core/src/main/java/com/google/common/truth/Platform.java#L156

And the only reference to that should be here:
https://github.com/google/truth/blob/release_1_1_1/core/src/main/java/com/google/common/truth/ComparisonFailureWithFacts.java#L30

And the only reference to that should be the guarded one here:
https://github.com/google/truth/blob/release_1_1_1/core/src/main/java/com/google/common/truth/FailureMetadata.java#L190

And the (Google-internal) test I added, which fails without my changes, passes with them. So something interesting is going on.... I've cloned your repo, and I'm investigating.

**Comment by cpovirk** [comment]
I can confirm that I can reproduce it in your project. For my reference, my debugging steps so far:

```
$ git co b87e1f5

$ ./gradlew dependencies --write-locks

$ vi $(grep -rl TruthJUnit src)
... remove references ...

$ vi build.gradle.kts
... edit `test` to contain `jvmArgs("-verbose:class")`

$ ./gradlew test --tests '*AndroidIntegrationTest*missing annotated packages option*' &> /tmp/everything
```

**Comment by tbroyer** [comment]
I pushed my changes to a branch: https://github.com/tbroyer/gradle-nullaway-plugin/tree/truth-1.1.1
And the build indeed fails: https://github.com/tbroyer/gradle-nullaway-plugin/runs/1750883855

**Comment by cpovirk** [comment]
Thanks.

Even `-XX:+TraceClassLoading` and `-XX:+TraceClassResolution` do not clear things up for me. But then I had never even heard of those until just now, so I don't necessarily know how to interpret them :)

I have dumped all the bytecode in the Truth jar, and the only references to `ComparisonFailure` are the expected ones from `Platform.PlatformComparisonFailure`.

`Platform.PlatformComparisonFailure` is in turn referenced from `ComparisonFailureWithFacts`, also as expected. But it also shows up in the bytecode for `Platform` (in `InnerClasses`), and maybe that's biting us?

**Comment by cpovirk** [comment]
Perhaps more likely: The `try`-`catch` approach in `FailureMetadata.failEqualityCheck` (which is indeed the only reference to `ComparisonFailureWithFacts`) is not good enough. I seem to recall that Java is allowed to load classes sooner than you might hope:

> [Errors detected during linkage are thrown at a point in the program where some action is taken by the program that might, directly or indirectly, require linkage to the class or interface involved in the error.](https://docs.oracle.com/javase/specs/jvms/se14/html/jvms-5.html#jvms-5.4)

Probably we should use reflection. There's always the chance that that will break something else, but "luckily" we do at least some of that already:
https://github.com/google/truth/blob/release_1_1_1/core/src/main/java/com/google/common/truth/Platform.java#L98

**Comment by cpovirk** [comment]
Backing up a bit as I wait for some tests to run:

Thanks for [your workaround above](https://github.com/google/truth/issues/333#issuecomment-765616282): It's probably the best current solution for people willing to go to the trouble to set it up, since it lets Truth continue to throw a true `ComparisonFailure`, which can be displayed more nicely by IDEs and other tools.

Still, I'm working on the reflective approach so that people who want to simply exclude JUnit without worrying about re-including it at runtime can get by with that simpler approach.

**Comment by cpovirk** [comment]
Using reflection fixes it.

Sorry, I should have known better: I'd heard warnings about the problem with this approach before, but I confused it with a different approach that actually _is_ safe (in which the class is used inside an `if` with an appropriate condition).

I wonder if we will ever see similar problems in Guava if `sun.misc.Unsafe` really, truly goes away -- such as here:
- https://github.com/google/guava/blob/d3c306e9e4220d80f111348a92f5cb56d8ad965c/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L151
- https://github.com/google/guava/blob/d3c306e9e4220d80f111348a92f5cb56d8ad965c/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L1249

**Comment by cpovirk** [comment]
OK, [1.1.2](https://github.com/google/truth/releases/tag/release_1_1_2) contains the fix (and another fix that I noticed I needed along the way...). Sorry for all the trouble.

It's still conceivable that _something_ will go wrong in _some_ case ([`InnerClasses`](https://github.com/google/truth/issues/333#issuecomment-765649934)?). But I have dealt with the one definite problem, which those following along at home may recognize as [Java Puzzler](http://www.javapuzzlers.com/) 44 (as Martin Buchholz points out to me).

Please continue to let us know of new problems that the JUnit dependency causes. The ones I'm aware of:
- JUnit 5 users end up with [2 annotations named `@Test` on their classpath](https://github.com/google/truth/issues/333#issuecomment-365034108). This seems to be affecting a fair number of people. They may want to put tests/pre-commit hooks/static analysis in place to catch this error, and they may wish to employ [tbroyer's approach of a runtime-only dependency on JUnit 4](https://github.com/google/truth/issues/333#issuecomment-765616282), which lets Truth continue to [throw a `ComparisonFailure` for better error reporting](https://github.com/google/truth/issues/333#issuecomment-765677646). Or, as of 1.1.2, they can just exclude our JUnit 4 dependency.
- [IntelliJ tries to look for JUnit 4 tests.](https://github.com/google/truth/issues/333#issuecomment-763884845) This week's report was the first I recall about that. As with the previous problem, those affected should be able to exclude the JUnit 4 dependency after upgrading to 1.1.2. They might also be able to employ tbroyer's workaround, but I'm unsure.

**Comment by KevinMcT** [comment]
1.1.2 looks good 👍  @cpovirk. No more broken window spam when utilizing truth in projects with jupiter and excluding junit.

(Work with stolsvik, so ack from us)

**Comment by MariusVolkhart** [comment]
@cpovirk the `ExpectFailure` class extends from `JUnitTestRule` which extends JUnit 4's `TestRule`. So when excluding JUnit 4, code referencing `ExpectFailure` no longer works. This includes code using the `expectFailureAbout` factory method

**Comment by tbroyer** [comment]
And that's, uh, expected: https://github.com/google/truth/releases/tag/release_1_1_2

> (JUnit 4 is still required for some advanced features, like `Expect`, `ExpectFailure`, and `TruthJUnit.assume()`.)

**Comment by MariusVolkhart** [comment]
🤦 missed that, thanks!

**Comment by cpovirk** [comment]
We don't have a clear plan for JUnit 5 at this point :(

I want to say that we ought to be able to extract the purely static version of ExpectFailure into a class with no JUnit dependency, but I'd have to confirm. And ideally, we'd want to get at least the beginnings of a long-term plan before copying things around.

In the meantime, copying and pasting the methods from ExpectFailure doesn't require *too* much duplication, so it may be a workable option (depending on licensing and other such questions).

**Comment by astubbs** [comment]
Related: Nicer way to support soft assertions (Expect.create junit4 Rule) in JUnit5? #893 (patch available)

**Comment by TWiStErRob** [comment]
@cpovirk is this still on hold?

**Comment by cpovirk** [comment]
Truth still declares a build dependency on JUnit:
https://github.com/google/truth/blob/ceecbd47b18d668bf1cb2d4b75138a9e49e8d77c/core/pom.xml#L21-L24

As of [Truth 1.1.2](https://github.com/google/truth/releases/tag/release_1_1_2), you can exclude that dependency, and Truth will work at runtime. (It just won't throw a `ComparisonFailure`.)

That's as far as we're likely to take this for a long while, unfortunately.

**Comment by TWiStErRob** [comment]
If that's the case would it make sense to document how to use Truth with JUnit 5 with detail on what features are lost to that exclusion and how to get them back in JUnit 5? I really like how detailed https://truth.dev/comparison is, would love to see a similar page for JUnit 5.

**Comment by cpovirk** [comment]
It would :( Truth is very much on the back burner. I do hope to change that someday.

Offhand, I think you lose only `ComparisonFailure` and the "`assertThat` alternatives," which are `Expect`, `ExpectFailure`, and `TruthJUnit.assume()` (noted in the 1.1.2 page). We don't have alternatives for them at the moment, nor do I know enough JUnit 5 to confidently sketch what they would look like (though I'd expect it to be _relatively_ straightforward).

**Comment by nlisker** [comment]
I used the gradle `exclude` declaration to avoid Junit 4 on the classpath. Is it not possible to declare the dependency as an internal implementation detail and require the user to pull in whichever Junit version they want? That is, it shouldn't be transitive.

**Comment by cpovirk** [comment]
Nothing is imminent here, but I think it's likely that we'll take additional incremental action here in the future. The main thing would probably be to copy most of what's in [`ExpectFailure`](https://truth.dev/expectfailure) to a new class ("`SubjectTesting`" or something) so that it can be used without the JUnit 4 dependency. Then we would be at the point that all JUnit-4-specific functionality is either (a) possible to avoid by avoiding JUnit-4-specific classes or (b) used conditionally when JUnit 4 is present at runtime.

Maybe we'll also get around to using the opentest4j exception/error classes. At first, that would likely mean only `AssertionFailedError`—and only in the cases when we would today use the JUnit 4 `ComparisonFailure` if it were on the classpath but we find that it's not. That particular step is one for which I _think_ we could probably take a PR if it did everything reflectively. But I may be forgetting things, so please only try it out if you think it's straightforward and would be willing to be disappointed if I realize there's some remaining obstacle.
