### ISSUE TITLE
[0.41] - D8: Program type already present: afu.org.checkerframework.checker.nullness.NullnessUtils

### ISSUE THREAD

**Issue by jaredsburrows** [google/truth#472]
## Repro:
1. `git clone https://github.com/jaredsburrows/android-gif-example`
2. Update Truth from `0.40` to `0.41`
3. `gradlew connectedDebugAndroidTest` 

## Error:
```
$ gradlew connectedDebugAndroidTest -s

> Task :compileDebugJavaWithJavac
Note: /Users/noname/repo/android-gif-example/build/generated/source/kapt/debug/burrows/apps/example/gif/di/component/DaggerAppComponent.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :assembleDebug
Total APK Size in android-gif-example-debug.apk in bytes: 3797277 (3.8 mb)

> Task :transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest FAILED
D8: Program type already present: afu.org.checkerframework.checker.nullness.NullnessUtils

> Task :countDebugDexMethods
Dexcount name:    dexcount-gradle-plugin
Dexcount version: 0.8.2
Dexcount input:   /Users/noname/repo/android-gif-example/build/outputs/apk/debug/android-gif-example-debug.apk
Total methods in android-gif-example-debug.apk: 49191 (75.06% used)
Total fields in android-gif-example-debug.apk:  27850 (42.50% used)
Total classes in android-gif-example-debug.apk:  6488 (9.90% used)
Methods remaining in android-gif-example-debug.apk: 16344
Fields remaining in android-gif-example-debug.apk:  37685
Classes remaining in android-gif-example-debug.apk:  59047

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/149.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/150.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/151.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/152.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/153.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/154.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/155.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/156.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/157.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/158.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/159.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/160.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/161.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/162.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/163.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/164.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/165.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/166.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/167.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/168.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/169.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/170.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/171.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/172.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/173.jar

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/149.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/150.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/151.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/152.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/153.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/154.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/155.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/156.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/157.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/158.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/159.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/160.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/161.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/162.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/163.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/164.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/165.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/166.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/167.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/168.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/169.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/170.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/171.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/172.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/173.jar
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/149.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/150.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/151.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/152.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/153.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/154.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/155.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/156.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/157.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/158.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/159.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/160.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/161.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/162.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/163.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/164.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/165.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/166.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/167.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/168.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/169.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/170.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/171.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/172.jar, /Users/noname/repo/android-gif-example/build/intermediates/transforms/dexBuilder/androidTest/debug/173.jar
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
        at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 43 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:67)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
        ... 48 more
Caused by: com.android.tools.r8.utils.AbortException
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
        ... 51 more


* Get more help at https://help.gradle.org

BUILD FAILED in 35s
56 actionable tasks: 55 executed, 1 up-to-date
```

**Comment by gabrielittner** [comment]
See #467

**Comment by JakeWharton** [comment]
#467

**Comment by jaredsburrows** [comment]
Thanks.
```
androidTestImplementation(extra["truth"] as String) { exclude(module = "checker-qual") }
```
