### ISSUE TITLE
NoSuchMethodError on OptionalSubject.hasValue() when comparison is not equal

### ISSUE THREAD

**Issue by mcmasjc3** [google/truth#519]
When I assertThat(anOptional).hasValue(expectedValue) and anOptional does not contain that value, the test errors on a NoSuchMethodError.  Stack trace is:

java.lang.NoSuchMethodError: com.google.common.base.Strings.lenientFormat(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

	at com.google.common.truth.LazyMessage.toString(LazyMessage.java:41)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.google.common.truth.Subject$3.apply(Subject.java:741)
	at com.google.common.truth.Subject$3.apply(Subject.java:738)
	at com.google.common.truth.FailureMetadata.description(FailureMetadata.java:289)
	at com.google.common.truth.FailureMetadata.descriptionAsFacts(FailureMetadata.java:306)
	at com.google.common.truth.FailureMetadata.failEqualityCheck(FailureMetadata.java:181)
	at com.google.common.truth.Subject.failEqualityCheck(Subject.java:913)
	at com.google.common.truth.Subject.standardIsEqualTo(Subject.java:193)
	at com.google.common.truth.Subject.isEqualTo(Subject.java:187)
	at com.google.common.truth.OptionalSubject.hasValue(OptionalSubject.java:77)
	at com.averoinc.labor.repository.mongo.MongoLaborRepositoryTimeCardTest.replaceTimeCard(MongoLaborRepositoryTimeCardTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by cpovirk** [comment]
Sounds like you'll have to update your Guava version to [25.1](https://github.com/google/guava/releases/tag/v25.1) or higher. Compare https://github.com/google/truth/issues/466 (and https://github.com/google/truth/issues/473).
